### ISSUE TITLE
SAML Version and funding requests unclear in documentation

### ISSUE THREAD

**Issue by AlHolden** [GiancarloGomez/ColdFusion-OneLogin#2]
Except for the possible hint of 1.0 in the application.name - I can't find any indication of which version of SAML this application will work on (1 or 2). Also how/where to send in any licensing gratuity.

**Comment by GiancarloGomez** [comment]
Hey Al, it's been a while since I wrote this and really have not had a use for it since back then. I am sure it is 1.0, if you can see what the date of 2.0 was released and if it was after Aug 27, 2014 then it is possibly only 1.0. What do you mean by licensing gratuity?

**Comment by AlHolden** [comment]
Hi Giancarlo;

Sorry for the delay, thanks for reaching out. I'd like to incorporate some
parts of your code into a SSO module to be used by an internal application
for a client. I think they're using SAML2 via Peoplesoft, and I hope I can
tweak a couple variables in your OneLogin version for that. What do you
think?

Plus, I want to confirm that our ability to do this is OK with you, even
send you a little $$ as appreciation for your work, perhaps via PayPal or
Dwolla. That's what I meant.

Alan K Holden
akh.com

**Comment by GiancarloGomez** [comment]
Hey Al,

You are free to use this code as you please, reason I share it :-). In regards to $$ for my work it is not required but greatly appreciated, if you would like to donate something you can do so to my PayPal account jc@fusedevelopments.com, thank you!
